config/routes.rb
Rails.application.routes.draw do
  resources :portfolios

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'index' => 'welcome#index'
  get 'contact' => 'welcome#contact'
  get 'portfolio' => 'portfolios#index'

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:work, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@united_states = {"Capital City" => "Washington, DC", 
                     "Favorite City" => "Honolulu, HI", 
                     "Favorite State" => "Hawaii", 
                     "Flag Colors" => "Red, White Blue"
                 }
    @korean  = ["kalbi.JPG", "bibim.JPG", "banchan.JPG"]
    @kalbi   = "kalbi.JPG"
  end

  def about
        @me = ["me.JPG"]
        @me1   = "me1.JPG"
  end

  def contact
      @travel = "travel.JPG"
      @me = "me.JPG"
      @me1   = "me1.JPG"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Showcase</title> <!-- This is the title for my tab -->
  <!-- These links are used to utilize bootstrap -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>

<!-- This is where I start my page styling -->
  <style>
    body {background-color: #E8E8E8;
      text-align: center;
      color: purple;
      font-family: Georgia;
      margin: 0;
      padding: 0;
      }
    .images { width:250px; 
      height:200px;
      border: solid 2px #787878;
      border-radius: 25px;
      }
</style>

</head>
<body>

<!-- This is my bootstrap nav bar -->

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/portfolio">Portfolio</a></li>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :work %><br>
    <%= f.text_field :work %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h2 style= "color:black; text-align: left; margin-left:25px;">Portfolio </h2> 

<h1>My Portfolio</h1>
<br/><br/><br/>
<div class="row">
    <% @portfolios.each do |portfolio| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= portfolio.work %></h2>
         <h3><%= portfolio.description %></h3>
       
         <div class="btn-group">
          <%= link_to 'Show', portfolio, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_portfolio_path(portfolio), class: "btn btn-default" %>
          <%= link_to 'Delete', portfolio, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Portfolio', new_portfolio_path, class: "btn btn-primary" %>

app/views/portfolios/new.html.erb
<h1>New portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Work:</strong>
  <%= @portfolio.work %>
</p>

<p>
  <strong>Description:</strong>
  <%= @portfolio.description %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>

app/views/welcome/about.html.erb
<h2 style= "color:black; text-align: left; margin-left:25px;">About </h2> 
<br/><br/><br/>

<% @me.each do |pic| %>
    <%= image_tag pic, class: "images" %> 
  <% end %>
 
<br/><br/><br/><br/> 

<h2>About Culinary Travels!</h2> <br/>
<h4>Culinary Travels is a food blog for folks who like to travel and eat. </h4> 
<h4>The blog features recipes and photos of foods from around the world that have been tasted by our Author.</h3>
<br/><br/>

<h2>About the Author!</h2> <br/>
<h4>Raquel Stalcup is the author of the Culinary Travels food blog. </h4> 
<h4>She enjoys sharing her travels and culinary experiences from around the world.</h4>
<h4>In addition to her food blog, Raquel is writing a cook book of her favorite dishes, </h4>
<h4>including her family recipes from Korea, Japan, Hawaii, and Germany. </h4>

app/views/welcome/contact.html.erb
<h2 style= "color:black; text-align: left; margin-left:25px;">Contact </h2> 

<h1> Contact Me!</h1>
<br/><br/>



<h4>Raquel.Stalcup@careerbuilder.com</h4>

<!--<style>
  .images { width:120px; 
      height:145px;
      border: solid 2px black;
      border-radius: 15px;
      }
</style>
<%= image_tag @me1, class: "images" %> 
<br/><br/><br/>-->

app/views/welcome/index.html.erb
<html>
<head>
<style>
  table, th, td {
	 border: 1px solid black;
	 width: 1000px;
	 height: 50px;
    text-align: center;
    margin-left: 25%;
   }
</style>
</head>

<body>
<h2 style= "color:black; text-align: left; margin-left:25px;">Home </h2> 

<h1>Culinary Travels</h1>
<br/>
<h1>Korean food</h1>
<br/><br/><br/>

  <% @korean.each do |pic| %>
    <%= image_tag pic, class: "images" %> 
  <% end %>
 
<br/><br/>    
<p>Kalbi, Bibim-Bop, and Banchan are popular Korean dishes </p>
<br/>
<p>Kalbi is Korean Barbequed Beef Short Ribs.</p>
<p>The short ribs are marinated in soy sauce, brown sugar, sesame oil, garlic, and mirin</p>
<p>and grilled over an open flame or cooked on a cast iron grill.</p>
<br/>
<p>Bibim-Bop, which means "mixed rice", consists of a bowl of rice topped with a variety of vegetables,</p>
<p>korean pepper paste, sunny-side-up egg, and sliced meat.</p>
<br/>
<p>Banchan are side dishes that are served alongside all Korean meals</p>
<br/><br/> 

<h4>Kalbi Recipe</h4>
<p>Ingredients</p>
<p>5 pounds Korean style beef short ribs</p>
<p>1 cup brown sugar, packed</p>
<p>1 cup soy sauce</p>
<p>1/2 cup water</p>
<p>1/4 cup mirin ( rice wine)</p>
<p>1 small onion, peeled and finely grated</p>
<p>1 small Asian pear, peeled and finely grated</p>
<p>4 tablespoons minced garlic</p>
<p>2 tablespoons dark sesame oil</p>
<p>1/4 teaspoon black pepper</p>
<p>2 green onions, thinly sliced (optional)</p>
<h4>Directions</h4>
<p>Mix all ingredients.  Stack the beef ribs into a pan and cover with marinade.  Marinate overnight.</p>
<p>Cook on high heat or grill for 2-3 minutes each side.  Sprinkle with sesame seeds and sliced green onions.</p>
 



<!-- This activity was to create a table using hash
<table>
  <tr>
    <% @united_states.each do |key,value| %>
	  <th><%= key %></th>
    <% end %>
  </tr>
  <tr>
    <% @united_states.each do |key,value| %>      
      <% if value.kind_of?(Array) %>
          <td><%= value.join(", ") %></td>
      <% else %>
         <td><%= value %></td>
      <% end %> 
    <% end %>
  </tr>
</table>
-->


</body>
</html>